// For Reducer CreateOrder
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

// For Reducer OrderDetails
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

// For Reducer OrderPay
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

// For Reducer ListOrders
export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST'
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS'
export const LIST_ORDER_FAIL = 'LIST_ORDER_FAIL'

// For Reducer ListMyOrders
export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST'
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS'
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL'
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET'

// For Reducer DelieverOrder
export const ORDER_DELIEVER_REQUEST = 'ORDER_DELIEVER_REQUEST'
export const ORDER_DELIEVER_SUCCESS = 'ORDER_DELIEVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIEVER_RESET = 'ORDER_DELIEVER_RESET'
